import '../core/event.dart';
import '../core/severity.dart';
import 'report_model.dart';

/// Exports a [DevBuddyReport] as GitHub-flavored Markdown.
///
/// Suitable for pasting into GitHub issues, PRs, or documentation.
class MarkdownExporter {
  /// Generate Markdown from a diagnostic report.
  String export(DevBuddyReport report) {
    final buf = StringBuffer();

    buf.writeln('# DevBuddy Diagnostic Report');
    buf.writeln();
    buf.writeln('**Generated:** ${report.generatedAt.toIso8601String()}');
    buf.writeln();

    // Device info
    if (report.deviceInfo.isNotEmpty) {
      buf.writeln('## Device Info');
      buf.writeln();
      buf.writeln('| Key | Value |');
      buf.writeln('|-----|-------|');
      for (final entry in report.deviceInfo.entries) {
        buf.writeln('| ${entry.key} | ${entry.value} |');
      }
      buf.writeln();
    }

    // Summary
    final critical = report.events.where((e) => e.severity == Severity.critical).length;
    final warnings = report.events.where((e) => e.severity == Severity.warning).length;
    final info = report.events.where((e) => e.severity == Severity.info).length;

    buf.writeln('## Summary');
    buf.writeln();
    buf.writeln('| Severity | Count |');
    buf.writeln('|----------|-------|');
    if (critical > 0) buf.writeln('| ${Severity.critical.emoji} Critical | $critical |');
    if (warnings > 0) buf.writeln('| ${Severity.warning.emoji} Warning | $warnings |');
    if (info > 0) buf.writeln('| ${Severity.info.emoji} Info | $info |');
    buf.writeln('| **Total** | **${report.events.length}** |');
    buf.writeln();

    if (report.events.isEmpty) {
      buf.writeln('> No diagnostic events recorded.');
      return buf.toString();
    }

    // Events grouped by module
    final byModule = <String, List<DevBuddyEvent>>{};
    for (final event in report.events) {
      byModule.putIfAbsent(event.module, () => []).add(event);
    }

    for (final entry in byModule.entries) {
      buf.writeln('## ${entry.key}');
      buf.writeln();
      for (final event in entry.value) {
        buf.writeln('### ${event.severity.emoji} ${event.title}');
        buf.writeln();
        buf.writeln(event.description);
        buf.writeln();
        if (event.suggestions.isNotEmpty) {
          buf.writeln('**How to fix:**');
          for (final suggestion in event.suggestions) {
            buf.writeln('- $suggestion');
          }
          buf.writeln();
        }
      }
    }

    buf.writeln('---');
    buf.writeln('*Generated by [DevBuddy](https://pub.dev/packages/dev_buddy)*');

    return buf.toString();
  }
}
