import 'package:dev_buddy_engine/dev_buddy_engine.dart';
import 'package:test/test.dart';

void main() {
  group('MarkdownExporter', () {
    final exporter = MarkdownExporter();

    test('generates valid markdown for empty report', () {
      final report = DevBuddyReport(
        events: const [],
        generatedAt: DateTime(2026, 3, 28),
      );

      final md = exporter.export(report);
      expect(md, contains('# DevBuddy Diagnostic Report'));
      expect(md, contains('No diagnostic events recorded'));
    });

    test('includes severity summary table', () {
      final report = DevBuddyReport(
        events: [
          DevBuddyEvent(
            module: 'performance',
            severity: Severity.critical,
            title: 'Jank',
            description: 'Frame drop',
            suggestions: ['fix it'],
          ),
          DevBuddyEvent(
            module: 'performance',
            severity: Severity.warning,
            title: 'Slow',
            description: 'Slow frame',
            suggestions: [],
          ),
        ],
        generatedAt: DateTime(2026, 3, 28),
      );

      final md = exporter.export(report);
      expect(md, contains('Critical'));
      expect(md, contains('Warning'));
      expect(md, contains('**Total** | **2**'));
    });

    test('includes event details with suggestions', () {
      final report = DevBuddyReport(
        events: [
          DevBuddyEvent(
            module: 'errors',
            severity: Severity.critical,
            title: 'Null Check Failed',
            description: 'The "!" operator was used on a null value.',
            suggestions: ['Replace "!" with "??"', 'Check initialization'],
          ),
        ],
        generatedAt: DateTime(2026, 3, 28),
      );

      final md = exporter.export(report);
      expect(md, contains('### 🔴 Null Check Failed'));
      expect(md, contains('**How to fix:**'));
      expect(md, contains('- Replace "!" with "??"'));
    });

    test('groups events by module', () {
      final report = DevBuddyReport(
        events: [
          DevBuddyEvent(
            module: 'performance',
            severity: Severity.warning,
            title: 'A',
            description: 'd',
            suggestions: [],
          ),
          DevBuddyEvent(
            module: 'network',
            severity: Severity.warning,
            title: 'B',
            description: 'd',
            suggestions: [],
          ),
        ],
        generatedAt: DateTime(2026, 3, 28),
      );

      final md = exporter.export(report);
      expect(md, contains('## performance'));
      expect(md, contains('## network'));
    });

    test('includes device info table', () {
      final report = DevBuddyReport(
        events: const [],
        generatedAt: DateTime(2026, 3, 28),
        deviceInfo: {'os': 'Android 14', 'model': 'Pixel 8'},
      );

      final md = exporter.export(report);
      expect(md, contains('## Device Info'));
      expect(md, contains('| os | Android 14 |'));
    });

    test('ends with DevBuddy attribution', () {
      final report = DevBuddyReport(
        events: [
          DevBuddyEvent(
            module: 'test',
            severity: Severity.info,
            title: 'T',
            description: 'd',
            suggestions: [],
          ),
        ],
        generatedAt: DateTime(2026, 3, 28),
      );

      final md = exporter.export(report);
      expect(md, contains('Generated by [DevBuddy]'));
    });
  });
}
